### ISSUE TITLE
Ask for keyed-for loop plan

### ISSUE THREAD

**Issue by khanhicetea** [dy/sprae#44]
Hi, thank you for the library

I want to ask is there any plan for support key in "each" directive ? 

Or even have a separate directive like ":each-key", depends on purpose (rendering sorting table)

Thanks!

**Comment by dy** [comment]
The rendering algorithm of sprae doesn't require key, since it maps array ops to dom directly. Do you have an example where it fails to render properly?

**Comment by dy** [comment]
The point is sprae doesn't use any dom diffing/swapping algo, because it directly maps list to DOM. In other words, if you remove or insert any elements to list - they're immediately reflected in DOM as is, in other words elements in array are tightly coupled with DOM elements. So there's not supposed to be situation when, say, we need to pass new list and diff it against existing list (matching current DOM), as react, uhtml etc do - whatever way you update the list, it immediately reflects in DOM.

If you find a case where sprae fails with that regard - please report. I am not aware of edge cases for now.

**Comment by khanhicetea** [comment]
Oh I see, I just ask for my curious. Thank you, I will test then report the edge cases. Have a nice week ! :)
